### PR TITLE
Add tabs

### PR DESCRIPTION
**Pull request by parkerpearson**
@brooksteve is this ready for merging into the main site? Any tasks left?

### CODE REVIEW

**Comment by StommePoes** [comment]
"active tab must always be visible/cannot be moved to 'more'" <-- this is going to be near-impossible to do if someone's active tab is the 7th of 8 tabs unless either
- tabs rearrange themselves per screen size which seems like a UI no-no
- the 'more' can be to the left (also not great)

Even if my current tab is #5 of 8 on a phablet with zooming on, I may well have room for "2 tabs + a more button" but unable to show the current active tab (because being #5 it would be under more).

**Comment by brooksteve** [comment]
Thanks Mallory! We were thinking the Tabs will rearrange themselves to
always show the active one. The idea came from a UX meeting and from a
usability stand point, it seemed worth the moving UI for the clarity of
knowing what tab is selected. What do you think? Any specific challenges we
need to address to make this happen?

**Comment by parkerpearson** [comment]
@StommePoes I'm not too worried about tabs rearranged themselves per screen size since resizing a screen isn't a huge use case, I would more expect a user to stick with a particular screen size during a session. I also don't think it would be any worse than the other rearrangement that would need to happen to fit desktop content in a smaller screen.

You can see an example of the behavior we are describing on the google search results page:

screen shot 2017-08-09 at 10 58 36 am
screen shot 2017-08-09 at 10 58 47 am

**Comment by StommePoes** [comment]
Google doesn't do responsive tabs that change their position based on what's been chosen-- they just make the whole page have a horizontal scroll bar.
google screenshot with Video chosen but cut off

**Comment by brooksteve** [comment]
It looks like Parker's example shows Google using the Tab behavior we want.
Clicking an option in "More" moves the selection out of the dropdown and
displays as a normal tab. Though, Google's search results page is not
responsive... Putting aside *if* we should move tabs - can we? Is this
reasonably straightforward?

**Pull request merged**
