### PR TITLE
First draft of component documentation for Typography

### PR DESCRIPTION
**Pull request by parkerpearson**

### CODE REVIEW

**Comment by parkerpearson** [comment]
@aarmour @edzee I went ahead and merged early so we can easily review the changes. http://pearson-higher-ed.github.io/design/docs/ui-components/typography/

**Comment by aarmour** [comment]
[Typography](http://pearson-higher-ed.github.io/design/docs/foundations/typography/) and [Colors](http://pearson-higher-ed.github.io/design/docs/foundations/colors/) also appear under the [Foundations](http://pearson-higher-ed.github.io/design/docs/foundations/) section.

**Comment by aarmour** [comment]
@parkerpearson A question about this statement: the lead "will automatically scale down for narrow viewports as well". This is not how it was implemented in [o-type](https://github.com/pearson-higher-ed/o-type), where small lead is a modifier, e.g.:

```html
<div class="o-type__lead">This is a regular lead. The style, including font size, is the same at all breakpoints</div>
<div class=""o-type__lead o-type__lead--small">This is a small lead. It provides less emphasis than a regular lead.</div>
```

**Comment by parkerpearson** [comment]
@aarmour The plan was to have it scale down at breakpoints like the titles
(<480px)

**Comment by parkerpearson** [comment]
Re foundations, I was thinking that would be more for the higher level design theory from the redesign, not the specific components that implement that thinking.

**Pull request merged**
