### PR TITLE
DES-272: Update dev documentation on contributing with changes due to Archetype component

### PR DESCRIPTION
**Pull request by aaronkaka**

### CODE REVIEW

**Comment by wyseguyonline** [comment]
Looks ok to me.

**Comment by parkerpearson** [comment]
Couple thoughts:

- I assume there should be more a11y requirements than just valid HTML?
- G1 and the Browser/Device support -> R1/2 are duplicates, the wording in R1 and R2 seems a little awkward.
- Some of the requirements are numbered incorrectly (e.g. start with 'R' instead of the relevant abbreviation for their section).
- The i18n and l10n sections are pretty terse, not sure if that's enough detail?
- The convention of UTF-8 could maybe be moved into General to simplify things?
- Maybe the same with ES6?

**Comment by aaronkaka** [comment]
@parkerpearson Good thoughts, I think I'd like to merge in what I've done so far and create a new user story for these suggestions.

**Comment by parkerpearson** [comment]
@aaronkaka okay, feel free to merge in then. Or I can merge if you want.

**Pull request merged**
