### PR TITLE
Update o-app-header docs

### PR DESCRIPTION
**Pull request by parkerpearson**
I also moved the file into an application-header folder so we can collect related images there, rather than a generic `img` folder at the root.

@aarmour @edzee 

Remaining tasks before this can be merged:

- [x] Include images/demos for each mode
- [x] Include up to date redlines
- [ ] Include .sketch and .ai mockups for other designers to use
- [x] Make sure there aren't any broken links

### CODE REVIEW

**Comment by aarmour** [comment]
REVEL only gets a single mode for special treatment: Legacy Course. Whatever goes into Integration mode needs to be available for all products. If it's not going to be stable, it needs to come out of the release.

**Comment by parkerpearson** [comment]
After talking it over with Joe I've updated the Integration Mode to match the acceptance criteria above.

**Comment by parkerpearson** [comment]
@aarmour what all needs to happen before we could embed demos of the header in the design definition?

**Comment by parkerpearson** [comment]
@Pearson-Higher-Ed/design-ux @aarmour I'm ready to merge this into the github pages branch now, we can come back and add the illustrator mockup later.

Let me know if anyone has objections before tomorrow.

**Pull request merged**
